### PR TITLE
Replace OSGi plugin with biz.aQute.bnd.

### LINKED ISSUE #13: Replace deprecated OSGi plugin
When running `./gradlew check --warning-mode all`, there's the following output:

```
> Configure project :
The osgi plugin has been deprecated. This is scheduled to be removed in Gradle 6.0. Consider using the biz.aQute.bnd plugin instead.
        at build_dq0pen3kf87bpqz0v7n08tc3t.run(/…/github/java-json-tools/jackson-coreutils/build.gradle:23)
```

[Replacing use of Gradle's deprecated OSGi Plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#replacing-use-of-gradles-deprecated-osgi-plugin)
https://docs.gradle.org/5.0/userguide/osgi_plugin.html

### PR DESCRIPTION
**Pull request by Capstan**
Fixes #13.

### CODE REVIEW

**Comment by Capstan** [comment]
Knowing little about OSGi, and seeing little configuration for it in the Gradle files, I'd like someone else to take a look at this before merging.

**Comment by huggsboson** [comment]
Do we know if we even need the osgi plugin anymore?  What fails if we remove it?

**Comment by huggsboson** [comment]
I scanned the build.gradle it doesn't look like we use the osgiManifest function introduced by that plugin, so I'd say we just remove it.

**Comment by Capstan** [comment]
I know so little about OSGi. This was somewhat spurred by requests to remove Guava due in issue #3 because it drastically increases the size of their JAX-RS web app, and java-json-tools/json-schema-core/pull/40 where they were having issues in the OSGi environment due to segregated classloaders. I presume people are using it this way, but we don't currently have any e2e testing for it.

/cc @soberich @borcsokj in case they have feedback on what / how it's used in OSGi.

**Comment by Capstan** [comment]
Also, according to https://docs.gradle.org/5.6.3/userguide/osgi_plugin.html, the OSGi plugin does affect the build without being otherwise referenced, by changing the manifest object, and adding a osgiClasses task.

https://github.com/bndtools/bnd/blob/4.2.0.REL/biz.aQute.bnd.gradle/README.md has some more details about how that plugin differs, but it looks like it similarly instruments the builds.

This isn't currently a priority for me to develop expertise in to make tests for, so I am relying on user feedback or contributions.

**Comment by huggsboson** [comment]
Thanks for the research.  Sounds good to me.

**Pull request merged**
